### ISSUE TITLE
Docs about server middleware out of date

### ISSUE THREAD

**Issue by ghostganz** [apollographql/persistgraphql#28]
The README says "middleware for Express servers in persistgraphql/lib/server", but there's no middleware to be found.
It also says "These will likely be moved to their own packages in the future", which I assume already has happened. Where did they go?

**Comment by stubailo** [comment]
We removed the middlewares because everyone's infrastructure will be a bit different - some people will load queries from an object, some from Redis, some from a database. So we replaced it with a simple short code snippet which people can modify to fit their needs: https://github.com/apollographql/persistgraphql#server-side

**Comment by stubailo** [comment]
I've removed the offending docs, and would appreciate some more code samples for how to, for example, load the queries from a database!

**Comment by Poincare** [comment]
We can go ahead and close this since the doc changes have been merged.
