### ISSUE TITLE
createBatchingNetworkInterface

### ISSUE THREAD

**Issue by mitjade** [apollographql/persistgraphql#3]
Would this also work with createBatchingNetworkInterface or just createNetworkInterface?

**Comment by Poincare** [comment]
At the moment, the `PersistedQueryNetworkInterface` subclasses the `HTTPFetchNetworkInterface` although it doesn't really have to do this. Would appreciate a PR that has it depend on a generic NetworkInterface instead!

**Comment by ramikhalaf** [comment]
@Poincare I'd like to take a stab at this, is there a contribution guide I can follow?

**Comment by Poincare** [comment]
@ramikhalaf Awesome! There isn't really a contribution guide but, here's basically the equivalent of one for this particular issue:

[This(https://github.com/apollographql/persistgraphql/blob/master/src/network_interface/ApolloNetworkInterface.ts) is where the network interface is currently implemented. What you probably want to do is replace this class with a method like `addPersistedQueries` that takes an Apollo Client Network Interface and changes it so that the query IDs are sent instead. Something like [this](https://github.com/apollographql/GitHunt-React/blob/master/ui/helpers/subscriptions.js), except that instead of adding two new methods, you want to replace one of the methods within the Apollo Client Network Interface. 

Please let me know if the above makes sense - I can answer questions along the way :)

**Comment by ramikhalaf** [comment]
@Poincare, the method we replace in this case is `fetchFromRemoteEndpoint(request, options)`?

**Comment by ramikhalaf** [comment]
@Poincare checkout #9 and let me know if theres anything I can make better!

**Comment by mitjade** [comment]
I see #9 was merged. Any chance of releasing this soon, so I can test it out.

**Comment by fubhy** [comment]
Great work. I opened a PR against apollo-client for the last necessary step (passing through the 'id' property on the request object when batching).

https://github.com/apollographql/apollo-client/pull/1302

**Comment by Poincare** [comment]
@mitjade Will be released tomorrow night - may be coupled with a couple of other small changes.

@fubhy Thanks! Getting batching working with persisted queries would be super cool.

**Comment by mitjade** [comment]
I seen this was now released and am trying to get this to work.
How would one change for example:

```javascript
      const client = createApolloClient(createBatchingNetworkInterface({
        uri: apiUrl,
        opts: {
          credentials: "same-origin",
          headers: req.headers,
        },
        batchInterval: 20,
      }));
```
to work with `PersistedQueryNetworkInterface `?

However I try to wrap or replace it with `PersistedQueryNetworkInterface `, I keep getting `TypeError: Cannot set property '_uri' of undefined`.

I have latest `apollo-client` 0.8.7 and `persistgraphql` 0.3.0 packages.

**Comment by mitjade** [comment]
Sorry, missed `addPersistedQueries(networkInterface: NetworkInterface, queryMap: OutputMap)` that is mentioned in readme.

**Comment by mitjade** [comment]
Was able to test this and it is working. Will close this now.
